### ISSUE TITLE
Add animation effect to text

### ISSUE THREAD

**Issue by shilik** [yivanscreations/lrc#2]
I have try to use animated Tex kit, but it didn't work.
Is there way to make the text animated when it is shown on the screen?

**Comment by Yivan000** [comment]
It seems like you're using this package in Flutter.

This package is just a LRC parser in pure Dart, and not a Flutter widget displaying LRC. I am planning another separate package for doing the latter, but no guarantees as of the moment.

Please respond if my assumption is wrong.

**Comment by Yivan000** [comment]
Closing this as this is not applicable to this package.
